import type {Metadata} from "next";
import {Electrolize, Inter} from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";

const inter = Inter({subsets: ["latin"]});
const electrolize = Electrolize({weight: '400', preload: false})

export const metadata: Metadata = {
    title: "Author",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={electrolize.className}>
        <body>
        {children}
        </body>
        </html>
    );
}
