import type {Metadata, Viewport} from "next";
import {Electrolize, Inter} from "next/font/google";
import "./globals.css";
import Head from 'next/head'

const inter = Inter({subsets: ["latin"]});
const electrolize = Electrolize({weight: '400', preload: false})

export const viewport: Viewport = {
    width: 'width=1024'
}

export const metadata: Metadata = {
    title: "Author",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={electrolize.className}>
        <Head>
            <meta name="viewport" content="width=1024" />
        </Head>
        <body>{children}</body>
        </html>
    );
}
